### ISSUE TITLE
show those row name we are interested in

### ISSUE THREAD

**Issue by QUEST2179** [DingWB/PyComplexHeatmap#18]
Dear Developer,

For show_rownames= True, could you please help how to only show those row name we are interested in? Thanks!

**Comment by DingWB** [comment]
You should use `anno_label`, instead of `show_rownames`. Please refer to[ this link](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#3.-Test-the-row-/-col-orders-&-add-selected-rows-labels), which will tell you how to show the selected feature names.
Briefly, you need to create a `anno_label` in row annotations. In the parameter `df` of `anno_label `,  index should be same as data in `ClusterMapPlotter `, while values should be either the names you want to show or NaN (the rows you do not want to show).

**Comment by QUEST2179** [comment]
great, thanks a lot for your quick response.

one more question, in HeatmapAnnotation if anno_label is put as first one, it goes to top or left, but sometimes in HeatmapAnnotation I only have anno_label no others like anno_simple, how can I make the label appears on right or bottom?

**Comment by DingWB** [comment]
This is a good question. Please refer to [this link](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#Change-orentation-to-the-right).
You can add a parameter `orientation` to change the direction. Please let me know whether it works for you.

**Comment by QUEST2179** [comment]
sorry orientation doesn't appear to work

**Comment by DingWB** [comment]
Could you please give me an example dataset so that I can debug it?

**Comment by DingWB** [comment]
Thanks for your feedback. It's really helpful for me to debug it. 
Please upgrade the package to the latest version (1.3.4) and refer to[ this link](https://github.com/DingWB/PyComplexHeatmap/blob/main/notebooks/Issue18.ipynb).
