### ISSUE TITLE
Incomplete display of column name

### ISSUE THREAD

**Issue by welyt** [DingWB/PyComplexHeatmap#7]
The picture does not display the full column name by default. I guess it may be due to occlusion (should all column names be displayed even if they are directly occluded?). I now solve this problem by increasing the width of the picture.
![image](https://user-images.githubusercontent.com/8581547/218360197-8c93d1dd-2503-4de0-82cf-7dc1429c9699.png)

**Comment by DingWB** [comment]
Yeah, you are right. If the width is not wide enough to show all the column labels, then you need to increase the width of the figure or decrease the font size of xlabels.

**Comment by AntoineCollin** [comment]
Hello,
First off, thanks for the amazing package ! I have a similar issue to the one raised here except part of the rows are not showing. I have a lot of row to show so i would like to avoid increasing the size of the image. Instead, I tried reducing the fontsize of the labels with yticklabels_kws={'labelsize':5} (i also tried tiny values) but the row still don't show all labels.

![image](https://github.com/DingWB/PyComplexHeatmap/assets/59394022/475045b2-5861-44ef-ac95-fc4bbf00fc62)

Do you have any idea how I could force it to display every labels and I can handle their sizes so that they don't overlap then ?

Thanks !

**Comment by DingWB** [comment]
Hello @AntoineCollin .
Thanks for your feedback, I just made some changes and have already uploaded it to pypi.
Could you please uninstall and install the latest version?
See https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#How-to-force-display-all-row/col-ticklabels?
