### ISSUE TITLE
Order messed after split rows

### ISSUE THREAD

**Issue by Bo-UT** [DingWB/PyComplexHeatmap#80]
hi, 

I  split the rows whiling clustering, but it seems the order is completed messed up. Is there any setting to fix the split order?
Thank you! 

```
cm = pch.ClusterMapPlotter(pd.DataFrame(res_dict),
                      row_cluster=True,
                      col_cluster=True,
                      row_dendrogram=True,
                      row_split=28,
                    #   show_rownames=True,
                    #   show_colnames=True,
                      cmap="YlOrRd", vmin=0, vmax=0.5)
```
![image](https://github.com/DingWB/PyComplexHeatmap/assets/55055062/592e55ec-ab76-4ba0-bf7e-79603624e868)

![image](https://github.com/DingWB/PyComplexHeatmap/assets/55055062/b8e6cf8c-590d-4d29-9d4e-b553152fc3f3)

**Comment by DingWB** [comment]
Hi @Bo-UT ,

For `row_split=int`, rows would be clustered according to the row dendrogram structure, you can not change the order as you want (otherwise, the row dendrogram tree could not be plotted).
To give a custom row_split_order, please use `row_split=pd.Series` or `row_split=pd.DataFrame` and give `row_split_order=list` to specify the order you want.
Another method is to sort the rows and columns before plotting and run ClusterMapPlotter with `row_cluster=False, col_cluster=False`.
Here are some relevant documentation: 
https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/cpg_modules.html#Plotting-the-Dot-clustermap
https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/single_cell_methylation.html#Visualizing-Single-Cell-DNA-Methylation-Data-(Loyfer2023)

**Comment by Bo-UT** [comment]
Hi @DingWB, 

Great. Thank you a lot!!
